[package]
name = "api"
version = "0.1.0"
edition = "2021"
description = "An API server for Investment web"
license = "MIT"

[dependencies]
actix-cors = "0.6"
actix-files = "0.6"
actix-multipart = "0.6"
actix-rt = "2.7"
actix-web = "4.1"
actix-web-httpauth = "0.8"